### ISSUE TITLE
Good First Issue

### ISSUE THREAD

**Issue by kataya1** [kataya1/Pinterest#2]
every one has made an issue: 
- [x] #5
- [x] #4
- [x] Kholoud made an issue
- [x] Moaz made an issue
- [ ] Sahar made an issue
- [x] #10

**Comment by Kholoud731** [comment]
if I commented will it be resolved?

**Comment by MoaazMoustafa** [comment]
Hello from the other side

**Comment by Kholoud731** [comment]
walahy ma fahm l mafrod n3ml a bas ha2felo

**Comment by Kholoud731** [comment]
hafta70 tany aho

**Comment by HassanTAli** [comment]
hi
